---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 29/10/2019 02:40
---

---@class RageUI
RageUI = {}

---@class Item
RageUI.Item = {}

---@class Panel
RageUI.Panel = {}

---@class Window
RageUI.Window = {}

---@class RMenu
RMenu = setmetatable({}, RMenu)

---@type table
local TotalMenus = {}

---Add
---@param Type string
---@param Name string
---@param Menu table
---@return RMenu
---@public
function RMenu.Add(Type, Name, Menu)
    if RMenu[Type] ~= nil then
        RMenu[Type][Name] = {
            Menu = Menu
        }
    else
        RMenu[Type] = {}
        RMenu[Type][Name] = {
            Menu = Menu
        }
    end
    return table.insert(TotalMenus, Menu)
end

---Get
---@param Type string
---@param Name string
---@return table
---@public
function RMenu:Get(Type, Name)
    if self[Type] ~= nil and self[Type][Name] ~= nil then
        return self[Type][Name].Menu
    end
end

---GetType
---@param Type string
---@return table
---@public
function RMenu:GetType(Type)
    if self[Type] ~= nil then
        return self[Type]
    end
end

---Settings
---@param Type string
---@param Name string
---@param Settings string
---@param Value any optional
---@return void
---@public
function RMenu:Settings(Type, Name, Settings, Value)
    if Value ~= nil then
        self[Type][Name][Settings] = Value
    else
        return self[Type][Name][Settings]
    end
end

---Delete
---@param Type string
---@param Name string
---@return void
---@public
function RMenu:Delete(Type, Name)
    self[Type][Name] = nil
    collectgarbage()
end

---DeleteType
---@param Type string
---@return void
---@public
function RMenu:DeleteType(Type)
    self[Type] = nil
    collectgarbage()
end

function RageUI.LoadBannerMenu()
    Banner = "https://cdn.discordapp.com/attachments/1342247405080416317/1369274406286790676/skdev.png?ex=681b43aa&is=6819f22a&hm=4adf938c39c18bb5741ea14474039eca27c75bf6d27a50c27428f1a630145841&"
    assert(Banner ~= nil and Banner ~= "skdev.png", "Please if you have Custom banner active then precise Valide Link to `iBoutique.Menu.Banner.LinkCustomBanner`");
     if not HasStreamedTextureDictLoaded("shop") then
    RequestStreamedTextureDict("shop", true)
    end
     while not HasStreamedTextureDictLoaded("shop") do Wait(1) end
     local TextureMenu = CreateDui(Banner, 480, 132);
    CreateRuntimeTextureFromDuiHandle(CreateRuntimeTxd("iShop_banner"), "banner_boutique", GetDuiHandle(TextureMenu));
     AddReplaceTexture("shop", "banner", "iShop_banner", "banner_boutique");
 end

 RageUI.LoadBannerMenu()